version: "3.9"

services:
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        env_file:
          - .env
        depends_on:
          postgres:
            condition: service_healthy
#        healthcheck:
#          test: curl --fail http://localhost:${CLIENT_PORT} || exit 1
#          interval: 10s
#          timeout: 5s
#          retries: 5
#          start_period: 10s

    postgres:
        image: postgres:15.2-alpine
        environment:
          PGDATA: /var/lib/postgresql/data
        env_file:
          - .env
        ports:
          - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
          - ./db-scripts:/docker-entrypoint-initdb.d
          - ./tmp/pgdata:/var/lib/postgresql/data
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 10s

volumes:
  tmp:
    external: true

