version: "3.9"
services:
  postgres:
    image: postgres:15.2-alpine
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DIALECT: ${DIALECT}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    external: true

